---
title: "mlviz"
author: "Ziqi Niu"
date: "2019/11/13"
output: html_document
---

```{r}
library(tidyverse)
library(factoextra)
library(pheatmap)
library(RColorBrewer)
library(gridExtra)
library(labdsv)
```

```{r}
foods <- read.csv('foods.csv', row.names = 1)
head(foods)
```



```{r}

f.out = prcomp(foods, scale = TRUE)
f = as.matrix(f.out$rotation)
fsc = f * pve
pheatmap(f, main = 'Correlation Matrix between Features and PCs', cluster_rows = F, cluster_cols = F)
```
```{r}
pves = data.frame(PrincipalComponents = c(1:10), pve)
pves

cpve = data.frame(PrincipalComponents = c(1:10), cumsum(pve))
```

```{r}
fvar = f.out$sdev^2
pve = fvar/sum(fvar)
pves = round(cumsum(pve)*100,2)

dat <- data.frame(PrincipalComponent=factor(1:10), CumulativeVariance=pves, PropVarExplained = round(pve*100,1))

a <- dat %>%
  ggplot(data = dat, mapping = aes(x = PrincipalComponent, y = PropVarExplained)) +
  geom_point() +
  geom_line(group=1, color='seagreen',lwd=1)+
  geom_text(label=round(pve*100, 1), nudge_x = 0.3, nudge_y = 0.7) +
  theme_minimal()+
  ggtitle('Scree Plot of Principal Components')+
  labs(x='Principal Component', y = 'Proportion of Variance Explained (%)')


b <- dat %>%
  ggplot(data = dat, mapping = aes(x=PrincipalComponent, y=CumulativeVariance)) +
  geom_point() +
  geom_line(group=1, color='darkblue', lwd=1)+
  geom_text(label=round(pves, 1), nudge_x = -0.3, nudge_y = 3) +
  theme_minimal()+
  ggtitle('Cumulative Variance Plot') +
  labs(x='Principal Component', y='Cumulative Variance (%)')

grid.arrange(a, b, ncol = 2)

```


```{r}
f.out$rotation
```


```{r}
f_norm = scale(f)

f_norm
```

```{r}
fs = f_norm*pve
pheatmap(fs, fontsize = 11, cluster_cols = F, cluster_rows = F, main = 'Correlation between Variables and PCs')
```



```{r}


```


```{r}
c <- fviz_pca_ind(f.out,
             col.ind = "cos2", # Color by the quality of representation
             #gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,     # Avoid text overlapping
             title = 'Scores on PC1 and PC2',
             xlab = 'PC1',
             ylab = 'PC2',
             legend = 0
             )
?fviz_pca_ind

```

```{r}
d <- fviz_pca_ind(f.out, axes = c(3, 4),
             col.ind = "cos2", # Color by the quality of representation
             #gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,    # Avoid text overlapping,
             legend = 0,
             title = 'Scores on PC3 and PC4',
             xlab = 'PC3',
             ylab = 'PC4'
             )

d
```


```{r}
fviz_pca_var(f.out,
             col.var = "contrib", # Color by contributions to the PC
             #gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r}
f.out$x
ranks <- data.frame(f.out$x)
```


